[package]
name = "s3tosx"
version = "0.1.0"
authors = ["Alice"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.6.1"
